### ISSUE TITLE
Error when using tracking = true

### ISSUE THREAD

**Issue by sanketp628** [timmeinhardt/trackformer#32]
In both cases, when I enable the tracking by either `tracking=true` in track.yaml or using `python src/train.py with  deformable tracking`, the program gives me an error saying

>   Traceback (most recent call last):
>   File "src/train.py", line 341, in <module>
>     train(args)
>   File "src/train.py", line 78, in train
>     model, criterion, postprocessors = build_model(args)
>   File "/media/overlord/Project/trackformer/src/trackformer/models/__init__.py", line 57, in build_model
>     model = DeformableDETRTracking(tracking_kwargs, detr_kwargs)
>   File "/media/overlord/Project/trackformer/src/trackformer/models/detr_tracking.py", line 145, in __init__
>     DETRTrackingBase.__init__(self, **tracking_kwargs)
>   File "/media/overlord/Project/trackformer/src/trackformer/models/detr_tracking.py", line 19, in __init__
>     super().__init__()
> 
> TypeError: __init__() missing 5 required positional arguments: 'backbone', 'transformer', 'num_classes', 'num_queries', and 'num_feature_levels'

Can you kindly tell me where I am going wrong? And what is the possible solution?
Thanks

**Comment by sanketp628** [comment]
[SOLVED]

detr_tracking.py had an extra line on line 19  >> `super().__init__()`

Remove it and the code should work as intended. Thanks
