### ISSUE TITLE
Not able to install MultiscaleDeformableAttention

### ISSUE THREAD

**Issue by mkhoshle** [timmeinhardt/trackformer#41]
Hi,

I am trying to run a test for training trackformer. I am looking at `INSTALL.md` to build the environment. When I try `python src/trackformer/models/ops/setup.py build --build-base=src/trackformer/models/ops/ install` I get an error saying:
```
Traceback (most recent call last):
  File "src/trackformer/models/ops/setup.py", line 62, in <module>
    setup(
  File "/z/home/mahzad-khosh/trackformer/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/z/home/mahzad-khosh/trackformer/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 148, in setup
    return run_commands(dist)
  File "/z/home/mahzad-khosh/trackformer/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
    dist.run_commands()
  File "/z/home/mahzad-khosh/trackformer/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "/z/home/mahzad-khosh/trackformer/lib/python3.8/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/z/home/mahzad-khosh/trackformer/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/z/home/mahzad-khosh/trackformer/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/z/home/mahzad-khosh/trackformer/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/z/home/mahzad-khosh/trackformer/lib/python3.8/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/z/home/mahzad-khosh/trackformer/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/z/home/mahzad-khosh/trackformer/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/z/home/mahzad-khosh/trackformer/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/z/home/mahzad-khosh/trackformer/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/z/home/mahzad-khosh/trackformer/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 580, in build_extensions
    build_ext.build_extensions(self)
  File "/z/home/mahzad-khosh/trackformer/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/z/home/mahzad-khosh/trackformer/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/z/home/mahzad-khosh/trackformer/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/z/home/mahzad-khosh/trackformer/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "/z/home/mahzad-khosh/trackformer/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 528, in build_extension
    objects = self.compiler.compile(sources,
  File "/z/home/mahzad-khosh/trackformer/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 414, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/z/home/mahzad-khosh/trackformer/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1135, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/z/home/mahzad-khosh/trackformer/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1413, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension
```
How can I get this package installed?

Thanks,

**Comment by timmeinhardt** [comment]
Do you have addtional error logs for the C++/CUDA compiling? And do u have the correct packages versions installed?

**Comment by mkhoshle** [comment]
Yes, I follow all the steps. When doing `pip install -r requirements.txt`, many packages fail because that specific version can not be found for example `opencv-python==4.2.0.34`. So I changed the version for those specific packages. Other than this I follow all the steps. 
Here are the info about my cuda version:
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Fri_Feb__8_19:08:17_PST_2019
Cuda compilation tools, release 10.1, V10.1.105
```

**Comment by timmeinhardt** [comment]
There is currently one issue with the `INSTALL.md`. It is supposed to read `2. Install PyTorch 1.7 and torchvision 0.8 from [here](https://pytorch.org/get-started/previous-versions/#v150).` But there shouldnt be any failing packpaes when running the first `pip install -r requirements.txt `.

**Comment by mkhoshle** [comment]
What python version should I use? Is it possible that the issue is caused by my python version?
Currently my python version is: `Python 3.10.4`

**Comment by timmeinhardt** [comment]
The `INSTALL.md` specifies `Install packages for Python 3.7`. Please follow it carefully and only change something if you feel confident to do so.

**Comment by mkhoshle** [comment]
Ok, when I do `conda install pytorch==1.7.0 torchvision==0.8.0 torchaudio==0.7.0 cudatoolkit=10.1 -c pytorch` I get the following message:
```
Collecting package metadata (current_repodata.json): done
Solving environment: \ 
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - defaults/linux-64::pip==21.2.2=py37h06a4308_0
  - defaults/linux-64::zlib==1.2.12=h7f8727e_2
  - defaults/linux-64::libgcc-ng==9.3.0=h5101ec6_17
  - defaults/linux-64::openssl==1.1.1n=h7f8727e_0
  - defaults/linux-64::ncurses==6.3=h7f8727e_2
  - defaults/linux-64::xz==5.2.5=h7f8727e_1
  - defaults/linux-64::readline==8.1.2=h7f8727e_1
  - defaults/noarch::wheel==0.37.1=pyhd3eb1b0_0
  - defaults/linux-64::certifi==2021.10.8=py37h06a4308_2
  - defaults/linux-64::libffi==3.3=he6710b0_2
  - defaults/linux-64::python==3.7.13=h12debd9_0
  - defaults/linux-64::tk==8.6.11=h1ccaba5_0
  - defaults/linux-64::libstdcxx-ng==9.3.0=hd4cf53a_17
  - defaults/linux-64::setuptools==61.2.0=py37h06a4308_0
  - defaults/linux-64::sqlite==3.38.3=hc218d9a_0
done
```
But it gets installed successfully. I am using python 3.7 and I followed all the steps. When doing the fifth step (`python src/trackformer/models/ops/setup.py build --build-base=src/trackformer/models/ops/ install`) I get the following error:
```
In file included from /z/home/mahzad-khosh/trackformer/src/trackformer/models/ops/src/vision.cpp:2:0:
/z/home/mahzad-khosh/trackformer/src/trackformer/models/ops/src/ms_deform_attn.h: In function ‘std::vector<at::Tensor> ms_deform_attn_backward(const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, int)’:
/z/home/mahzad-khosh/trackformer/src/trackformer/models/ops/src/ms_deform_attn.h:39:20: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
     if (value.type().is_cuda())
                    ^
In file included from /z/home/mahzad-khosh/env/trackformer/lib/python3.7/site-packages/torch/include/ATen/Tensor.h:3:0,
                 from /z/home/mahzad-khosh/env/trackformer/lib/python3.7/site-packages/torch/include/ATen/Context.h:4,
                 from /z/home/mahzad-khosh/env/trackformer/lib/python3.7/site-packages/torch/include/ATen/ATen.h:9,
                 from /z/home/mahzad-khosh/env/trackformer/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /z/home/mahzad-khosh/env/trackformer/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /z/home/mahzad-khosh/env/trackformer/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /z/home/mahzad-khosh/env/trackformer/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /z/home/mahzad-khosh/env/trackformer/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /z/home/mahzad-khosh/env/trackformer/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /z/home/mahzad-khosh/env/trackformer/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:8,
                 from /z/home/mahzad-khosh/env/trackformer/lib/python3.7/site-packages/torch/include/torch/extension.h:4,
                 from /z/home/mahzad-khosh/trackformer/src/trackformer/models/ops/src/cpu/ms_deform_attn_cpu.h:2,
                 from /z/home/mahzad-khosh/trackformer/src/trackformer/models/ops/src/ms_deform_attn.h:3,
                 from /z/home/mahzad-khosh/trackformer/src/trackformer/models/ops/src/vision.cpp:2:
/z/home/mahzad-khosh/env/trackformer/lib/python3.7/site-packages/torch/include/ATen/core/TensorBody.h:277:30: note: declared here
   DeprecatedTypeProperties & type() const {
                              ^~~~
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/z/home/mahzad-khosh/env/trackformer/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1522, in _run_ninja_build
    env=env)
  File "/z/home/mahzad-khosh/env/trackformer/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/trackformer/models/ops/setup.py", line 65, in <module>
    cmdclass={"build_ext": torch.utils.cpp_extension.BuildExtension},
  File "/z/home/mahzad-khosh/env/trackformer/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/z/home/mahzad-khosh/env/trackformer/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 148, in setup
    return run_commands(dist)
  File "/z/home/mahzad-khosh/env/trackformer/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
    dist.run_commands()
  File "/z/home/mahzad-khosh/env/trackformer/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "/z/home/mahzad-khosh/env/trackformer/lib/python3.7/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/z/home/mahzad-khosh/env/trackformer/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/z/home/mahzad-khosh/env/trackformer/lib/python3.7/site-packages/setuptools/_distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/z/home/mahzad-khosh/env/trackformer/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/z/home/mahzad-khosh/env/trackformer/lib/python3.7/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/z/home/mahzad-khosh/env/trackformer/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/z/home/mahzad-khosh/env/trackformer/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/z/home/mahzad-khosh/env/trackformer/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/z/home/mahzad-khosh/env/trackformer/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/z/home/mahzad-khosh/env/trackformer/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 653, in build_extensions
    build_ext.build_extensions(self)
  File "/z/home/mahzad-khosh/env/trackformer/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/z/home/mahzad-khosh/env/trackformer/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/z/home/mahzad-khosh/env/trackformer/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/z/home/mahzad-khosh/env/trackformer/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "/z/home/mahzad-khosh/env/trackformer/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/z/home/mahzad-khosh/env/trackformer/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 482, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/z/home/mahzad-khosh/env/trackformer/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1238, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/z/home/mahzad-khosh/env/trackformer/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1538, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
```

**Comment by timmeinhardt** [comment]
The `INSTALL.md` instructions use `pip` and not `conda`. This means you need to work with a virtualenv and not cona. For the fifths step please check all your CUDA paths are correctly set.

**Comment by mkhoshle** [comment]
In order to build a virtual environment with python 3.7, I need to install Python 3.7 on my system, and actually, python3.7 isn’t available for Ubuntu 20.04. The default is 3.8. Is there any way around this?

**Comment by mkhoshle** [comment]
> https://pytorch.org/get-started/previous-versions/#v150

I managed to build a virtual env with Python 3.7. On step 2 however when I try `pip install torch==1.7.0+cu101 torchvision==0.8.0+cu101 torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html` I get this error:
```
Looking in links: https://download.pytorch.org/whl/torch_stable.html
Collecting torch==1.7.0+cu101
  Downloading https://download.pytorch.org/whl/cu101/torch-1.7.0%2Bcu101-cp37-cp37m-linux_x86_64.whl (735.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 735.3/735.3 MB 4.3 MB/s eta 0:00:00
ERROR: Could not find a version that satisfies the requirement torchvision==0.8.0+cu101 (from versions: 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.2, 0.2.2.post2, 0.2.2.post3, 0.3.0, 0.4.0, 0.4.0+cpu, 0.4.0+cu92, 0.4.1, 0.4.1+cpu, 0.4.1+cu100, 0.4.1+cu92, 0.4.2, 0.4.2+cpu, 0.4.2+cu100, 0.4.2+cu92, 0.5.0, 0.5.0+cpu, 0.5.0+cu100, 0.5.0+cu92, 0.6.0, 0.6.0+cpu, 0.6.0+cu101, 0.6.0+cu92, 0.6.1, 0.6.1+cpu, 0.6.1+cu101, 0.6.1+cu92, 0.7.0, 0.7.0+cpu, 0.7.0+cu101, 0.7.0+cu92, 0.8.0, 0.8.1, 0.8.1+cpu, 0.8.1+cu101, 0.8.1+cu110, 0.8.1+cu92, 0.8.2, 0.8.2+cpu, 0.8.2+cu101, 0.8.2+cu110, 0.8.2+cu92, 0.9.0, 0.9.0+cpu, 0.9.0+cu101, 0.9.0+cu111, 0.9.1, 0.9.1+cpu, 0.9.1+cu101, 0.9.1+cu102, 0.9.1+cu111, 0.10.0, 0.10.0+cpu, 0.10.0+cu102, 0.10.0+cu111, 0.10.0+rocm4.1, 0.10.0+rocm4.2, 0.10.1, 0.10.1+cpu, 0.10.1+cu102, 0.10.1+cu111, 0.10.1+rocm4.1, 0.10.1+rocm4.2, 0.11.0, 0.11.0+cpu, 0.11.0+cu102, 0.11.0+cu111, 0.11.0+cu113, 0.11.0+rocm4.1, 0.11.0+rocm4.2, 0.11.1, 0.11.1+cpu, 0.11.1+cu102, 0.11.1+cu111, 0.11.1+cu113, 0.11.1+rocm4.1, 0.11.1+rocm4.2, 0.11.2, 0.11.2+cpu, 0.11.2+cu102, 0.11.2+cu111, 0.11.2+cu113, 0.11.2+rocm4.1, 0.11.2+rocm4.2, 0.11.3, 0.11.3+cpu, 0.11.3+cu102, 0.11.3+cu111, 0.11.3+cu113, 0.11.3+rocm4.1, 0.11.3+rocm4.2, 0.12.0, 0.12.0+cpu, 0.12.0+cu102, 0.12.0+cu113, 0.12.0+cu115, 0.12.0+rocm4.3.1, 0.12.0+rocm4.5.2)
ERROR: No matching distribution found for torchvision==0.8.0+cu101
```

**Comment by mkhoshle** [comment]
I tried moving forward with PyTorch 1.5 and torchvision 0.6 as mentioned in `INSTALL.md`. But in the next steps when Installing pycocotools, I face the following error:
```
      x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/home/mahzad-khosh/.virtualenvs/trackformer/lib/python3.7/site-packages/numpy/core/include -I../common -I/home/mahzad-khosh/.virtualenvs/trackformer/include -I/usr/include/python3.7m -c pycocotools/_mask.c -o build/temp.linux-x86_64-cpython-37/pycocotools/_mask.o -Wno-cpp -Wno-unused-function -std=c99
      pycocotools/_mask.c:4:10: fatal error: Python.h: No such file or directory
          4 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pycocotools

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

**Comment by timmeinhardt** [comment]
The current INSTALL.md has the wrong

> There is currently one issue with the `INSTALL.md`. It is supposed to read `2. Install PyTorch 1.7 and torchvision 0.8 from [here](https://pytorch.org/get-started/previous-versions/#v150).` But there shouldnt be any failing packpaes when running the first `pip install -r requirements.txt `.

PyTorch 1.5 might not work. Why dont your try `pip install torch==1.7.1+cu110 torchvision==0.8.2+cu110 torchaudio==0.7.2 -f https://download.pytorch.org/whl/torch_stable.html`

**Comment by mkhoshle** [comment]
@timmeinhardt I was able to install torch using `pip install torch==1.7.1+cu101 torchvision==0.8.2+cu101 torchaudio==0.7.2 -f https://download.pytorch.org/whl/torch_stable.html`. However when Installing pycocotools, I face the same error:
```
      x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/home/mahzad-khosh/.virtualenvs/trackformer/lib/python3.7/site-packages/numpy/core/include -I../common -I/home/mahzad-khosh/.virtualenvs/trackformer/include -I/usr/include/python3.7m -c pycocotools/_mask.c -o build/temp.linux-x86_64-cpython-37/pycocotools/_mask.o -Wno-cpp -Wno-unused-function -std=c99
      pycocotools/_mask.c:4:10: fatal error: Python.h: No such file or directory
          4 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pycocotools

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

**Comment by mkhoshle** [comment]
@timmeinhardt I needed to do `sudo apt-get install python3.7-dev` to successfully install pycocotools. However, when installing `MultiScaleDeformableAttention` I get this error:
```
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/z/home/mahzad-khosh/.virtualenvs/trackformer/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1539, in _run_ninja_build
    env=env)
  File "/usr/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/trackformer/models/ops/setup.py", line 65, in <module>
    cmdclass={"build_ext": torch.utils.cpp_extension.BuildExtension},
  File "/z/home/mahzad-khosh/.virtualenvs/trackformer/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/z/home/mahzad-khosh/.virtualenvs/trackformer/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 148, in setup
    return run_commands(dist)
  File "/z/home/mahzad-khosh/.virtualenvs/trackformer/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
    dist.run_commands()
  File "/z/home/mahzad-khosh/.virtualenvs/trackformer/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "/z/home/mahzad-khosh/.virtualenvs/trackformer/lib/python3.7/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/z/home/mahzad-khosh/.virtualenvs/trackformer/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/z/home/mahzad-khosh/.virtualenvs/trackformer/lib/python3.7/site-packages/setuptools/_distutils/command/build.py", line 136, in run
    self.run_command(cmd_name)
  File "/z/home/mahzad-khosh/.virtualenvs/trackformer/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/z/home/mahzad-khosh/.virtualenvs/trackformer/lib/python3.7/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/z/home/mahzad-khosh/.virtualenvs/trackformer/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/z/home/mahzad-khosh/.virtualenvs/trackformer/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/z/home/mahzad-khosh/.virtualenvs/trackformer/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/z/home/mahzad-khosh/.virtualenvs/trackformer/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/z/home/mahzad-khosh/.virtualenvs/trackformer/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 670, in build_extensions
    build_ext.build_extensions(self)
  File "/z/home/mahzad-khosh/.virtualenvs/trackformer/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/z/home/mahzad-khosh/.virtualenvs/trackformer/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/z/home/mahzad-khosh/.virtualenvs/trackformer/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/z/home/mahzad-khosh/.virtualenvs/trackformer/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "/z/home/mahzad-khosh/.virtualenvs/trackformer/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/z/home/mahzad-khosh/.virtualenvs/trackformer/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 500, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/z/home/mahzad-khosh/.virtualenvs/trackformer/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1255, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/z/home/mahzad-khosh/.virtualenvs/trackformer/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1555, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
(trackformer) (base) mahzad-khosh@prism:/z/home/mahzad-khosh/trackformer$ 

```

**Comment by timmeinhardt** [comment]
This still means you are installing, compiling or linking a wrong cuda, cudnn or pytorch version.

**Comment by mkhoshle** [comment]
I check everything here:
```
(trackformer) (base) mahzad-khosh@prism:/z/home/mahzad-khosh/trackformer$ ipython
Python 3.7.13 (default, Apr 24 2022, 01:05:22) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.19.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import sys

In [2]: sys.version_info
Out[2]: sys.version_info(major=3, minor=7, micro=13, releaselevel='final', serial=0)

In [3]: import torch

In [4]: torch.__version__
Out[4]: '1.7.1+cu101'
```
I just followed all the instructions you provided. But I am not sure why this error keeps happening.

**Comment by mkhoshle** [comment]
@timmeinhardt I got MultiScaleDeformableAttention installed by using `cuda10.2` instead of `cuda10.1`. Thanks for your help.
