### ISSUE TITLE
Cuda is not available

### ISSUE THREAD

**Issue by Martinzhen** [timmeinhardt/trackformer#49]
hallo timmeinhardt

When I install MultiScaleDeformableAttention package: python src/trackformer/models/ops/setup.py build --build-base=src/trackformer/models/ops/ install :
I met an error.

```
(tfr) C:\Users\ztmar\mots\trackformer>python src/trackformer/models/ops/setup.py build --build-base=src/trackformer/models/ops/ install
Traceback (most recent call last):
  File "src/trackformer/models/ops/setup.py", line 64, in <module>
    ext_modules=get_extensions(),
  File "src/trackformer/models/ops/setup.py", line 41, in get_extensions
    raise NotImplementedError('Cuda is not available')
NotImplementedError: Cuda is not available
```

## Environment:

Provide your environment information using the following command:
```
PyTorch version: 1.7.1+cu101
Is debug build: False
CUDA used to build PyTorch: 10.1
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Home
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.22.5

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] torch==1.7.1+cu101
[pip3] torchaudio==0.7.2
[pip3] torchfile==0.1.0
[pip3] torchvision==0.8.2+cu101
[conda] Could not collect
```

**Comment by timmeinhardt** [comment]
Please check your CUDA installation and if all paths are set correctly. This issue goes beyond the support of this repository.

**Comment by JulianoLagana** [comment]
@timmeinhardt Is there a way to install this on a machine without a GPU?

**Comment by timmeinhardt** [comment]
You can install it, yes. But the code does not catch all CPU tensors. That is why you got the error above. In addition, processing sequences on a CPU is terribly slow.
