### ISSUE TITLE
Training Custom Dataset

### ISSUE THREAD

**Issue by ConsciousML** [timmeinhardt/trackformer#6]
Hi,

I try to train on a custom dataset (of one sample, attached to this issue), the data is not temporal.
I run the following command:
```bash
python src/train.py
    with \
    deformable \
    mot17 \
    resume=models/crowdhuman_train_val_deformable/checkpoint.pth \
    output_dir=models/boxy_train_deformable \
    mot_path=my_custom_dataset \
    train_split=train\ 
    val_split=val \
    epochs=50 \
```

As I train on static data (not temporal) I don't use the 'tracking' option.
Upon running the code I face an assert inside the generalized_box_iou function:
https://github.com/timmeinhardt/trackformer/blob/686fe60858e4f61497a4544b95f94487614d0741/src/trackformer/util/box_ops.py#L51

In fact, the both input contain nans.

Following the mentioned COCO style in the TRAIN.md, I followd the suggested structure and here is my sample of my train.json file:
```bash
{
    "type": "instances",
    "images": [
        {
            "file_name": "601038faba553c0015ac7c00_00000.png",
            "id": 0
        }
    ],
"annotations": [
        {
            "id": 0,
            "bbox": [
                464.0,
                0.0002879999999976235,
                241.000448,
                228.99974399999996
            ],
            "image_id": 3,
            "segmentation": [],
            "ignore": 0,
            "visibility": 1.0,
            "area": 55189.04089588531,
            "iscrowd": 0,
            "category_id": 0
        }
    ],
"categories": [
        {
            "supercategory": "human",
            "name": "person",
            "id": 0
        }
    ]
}
```

After investigation, I notice that the COCO annotation format uses box coordinates: [xtl, ytl, w, h],
where:
- xtl: the top left x
- ytl: the top left y
- w: width
- h: height

I'm I doing anything wrong ?

Best,
Axel

**Comment by timmeinhardt** [comment]
If you were able to reproduce our results by running the provided model file this issue is something you have to debug on your side. I would start with the data loading code and see if your sample is actually getting loaded and then work myself up the pipeline. If you run the Visdom server you should see your sample being visualized.

**Comment by ConsciousML** [comment]
Ok thanks for the response.

I see a command line example for train on temporal data:
```bash
python src/train.py with \
    deformable \
    tracking \
    mot17 \
    full_res \
    resume=models/mot17_train_deformable_private/checkpoint.pth \
    output_dir=models/custom_dataset_train_deformable \
    mot_path=data/custom_dataset \
    train_split=train \
    val_split=val \
    epochs=20 \
```

Quoting your paper:
```bash
Simulate MOT from single images. The encoderdecoder multi-level attention mechanism requires substantial amounts of training data. Hence, we follow a similar approach as in [56] and simulate MOT data from the CrowdHuman [43] person detection dataset. The adjacent training
frames t−1 and t are generated by applying random spatial
augmentations to a single image. To simulate high frame
rates as in MOT17 [28], we only randomly resize and crop
of up to 5% with respect to the original image size.
```

What I want to do is the exact same thing as training on CrowdHuman but with my own data.
Can you confirm that I'm using the right command line options please ?

I've been debugging since two days and I would appreciate if you could give me a little bit in the process.

Thanks !

**Comment by timmeinhardt** [comment]
Since you are loading the `mot17` config your command is correct if you want to train on a multi-object tracking dataset. But since this is not the case for you, you need to change a few things. For example:

```
python src/train.py with \
    deformable \
    tracking \
    crowdhuman \
    full_res \
    resume=models/mot17_train_deformable_private/checkpoint.pth \
    output_dir=models/custom_dataset_train_deformable \
    crowdhuman_path=data/custom_dataset \
    train_split=train \
    val_split=val \
    epochs=20 \
```

Your removal of the `tracking` option was wrong since you want to do tracking. But you dont want to do it on a tracking dataset but a static dataset which then simulates tracking frame-pairs.

**Comment by ConsciousML** [comment]
After trying this, I faced an assert here: https://github.com/timmeinhardt/trackformer/blob/686fe60858e4f61497a4544b95f94487614d0741/src/trackformer/datasets/crowdhuman.py#L12

I fixed it by changing `train_split=train` to `crowdhuman_train_split=train`.

Then I noticed that by leaving `mot_path` to the default `data/MOT17` it was searching for the `mot17` data here:
https://github.com/timmeinhardt/trackformer/blob/686fe60858e4f61497a4544b95f94487614d0741/src/trackformer/datasets/mot.py#L161

I guess I had to set also `mot_path=data/custom_dataset` as I don't want to train on `mot17` or `train_split` to `None` ?
https://github.com/timmeinhardt/trackformer/blob/686fe60858e4f61497a4544b95f94487614d0741/src/trackformer/datasets/mot.py#L190

It seems I now have a CUDA out of memory error. I will try on a bigger GPU.

Thanks again ! You were very helpful.

**Comment by ConsciousML** [comment]
I guess I got I little bit farther with:
```bash
python src/train.py with \
    deformable \
    tracking \
    crowdhuman \
    full_res \
    resume=models/mot17_train_deformable_private/checkpoint.pth \
    output_dir=models/boxy_train_deformable \
    crowdhuman_path=data/OutputCOCO \
    crowdhuman_train_split=train \
    mot_path=data/OutputCOCO \
    train_split=None \
    val_split=val \
    epochs=50 \
```

I tried on a single RTX 2080 Ti.

I somewhat completed an iteration:
```bash
Epoch: [1]  [  0/576]  eta: 0:15:55  lr: 0.000100  class_error: 100.00  loss: 10.7099 (10.7099)  loss_ce: 0.0060 (0.0060)  loss_bbox: 1.0678 (1.0678)  loss_giou: 0.8228 (0.8228)  loss_ce_0: 0.0066 (0.0066)  loss_bbox_0: 0.9433 (0.9433)  loss_giou_0: 0.7569 (0.7569)  loss_ce_1: 0.0057 (0.0057)  loss_bbox_1: 0.8870 (0.8870)  loss_giou_1: 0.7355 (0.7355)  loss_ce_2: 0.0067 (0.0067)  loss_bbox_2: 0.9318 (0.9318)  loss_giou_2: 0.7680 (0.7680)  loss_ce_3: 0.0079 (0.0079)  loss_bbox_3: 1.0584 (1.0584)  loss_giou_3: 0.7969 (0.7969)  loss_ce_4: 0.0064 (0.0064)  loss_bbox_4: 1.0801 (1.0801)  loss_giou_4: 0.8221 (0.8221)  loss_ce_unscaled: 0.0060 (0.0060)  class_error_unscaled: 100.0000 (100.0000)  loss_bbox_unscaled: 0.2136 (0.2136)  loss_giou_unscaled: 0.4114 (0.4114)  cardinality_error_unscaled: 1.0000 (1.0000)  loss_ce_0_unscaled: 0.0066 (0.0066)  loss_bbox_0_unscaled: 0.1887 (0.1887)  loss_giou_0_unscaled: 0.3785 (0.3785)  cardinality_error_0_unscaled: 1.0000 (1.0000)  loss_ce_1_unscaled: 0.0057 (0.0057)  loss_bbox_1_unscaled: 0.1774 (0.1774)  loss_giou_1_unscaled: 0.3677 (0.3677)  cardinality_error_1_unscaled: 1.0000 (1.0000)  loss_ce_2_unscaled: 0.0067 (0.0067)  loss_bbox_2_unscaled: 0.1864 (0.1864)  loss_giou_2_unscaled: 0.3840 (0.3840)  cardinality_error_2_unscaled: 1.0000 (1.0000)  loss_ce_3_unscaled: 0.0079 (0.0079)  loss_bbox_3_unscaled: 0.2117 (0.2117)  loss_giou_3_unscaled: 0.3985 (0.3985)  cardinality_error_3_unscaled: 1.0000 (1.0000)  loss_ce_4_unscaled: 0.0064 (0.0064)  loss_bbox_4_unscaled: 0.2160 (0.2160)  loss_giou_4_unscaled: 0.4110 (0.4110)  cardinality_error_4_unscaled: 1.0000 (1.0000)  lr_backbone: 0.0000 (0.0000)  time: 1.6596  data: 0.1928  max mem: 8921
```

but the next iteration causes a CUDA out of memory error:
```bash
RuntimeError: CUDA out of memory. Tried to allocate 164.00 MiB (GPU 0; 10.76 GiB total capacity; 9.73 GiB already allocated; 13.81 MiB free; 9.94 GiB reserved in total by PyTorch)
```

In the `cfgs/train.yaml` the `batch_size` is already at `1`.
Do you know what parameters I can change ?

Or the training is not feasible on a single RTX 2080 Ti ?

Have a great weekend !

**Comment by ConsciousML** [comment]
By reducing the values in `cfgs/train_full_res.yaml`, I don't get the out of memory.
But i still get the assertion in:
https://github.com/timmeinhardt/trackformer/blob/686fe60858e4f61497a4544b95f94487614d0741/src/trackformer/util/box_ops.py#L51

I plotted the boxes from my custom dataset and it seems fine.
Do you have any idea, from where it can come from ? Or any advise on how to debug it ?

**Comment by ConsciousML** [comment]
By the way, is it possible to perform the validation on static data ? (on CrowdHuman like dataset)

**Comment by timmeinhardt** [comment]
Yes it is possible to perform validation on static data but not for tracking metrics.

Try to use the Visdom visualization to see if your data is formatted correctly and have an overview on your losses etc.. Besides that it is hard to say where and why the error occurs if you dont provide the full stackstrace. Does the assert error happen during validation, trackign evaluation or somehwhere else?

**Comment by ConsciousML** [comment]
This is the stack trace:
```bash
Traceback (most recent call last):
  File "/home/bigbro/anaconda3/envs/trackformer/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/bigbro/anaconda3/envs/trackformer/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/bigbro/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/bigbro/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/home/bigbro/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/home/bigbro/anaconda3/envs/trackformer/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/home/bigbro/anaconda3/envs/trackformer/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/bigbro/anaconda3/envs/trackformer/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "src/train.py", line 336, in <module>
    train(args)
  File "src/train.py", line 263, in train
    visualizers['train'], args)
  File "src/trackformer/engine.py", line 106, in train_one_epoch
    outputs, targets, *_ = model(samples, targets)
  File "/home/bigbro/anaconda3/envs/trackformer/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "src/trackformer/models/detr_tracking.py", line 45, in forward
    prev_indices = self._matcher(prev_outputs_without_aux, prev_targets)
  File "/home/bigbro/anaconda3/envs/trackformer/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/bigbro/anaconda3/envs/trackformer/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "src/trackformer/models/matcher.py", line 94, in forward
    box_cxcywh_to_xyxy(tgt_bbox))
  File "src/trackformer/util/box_ops.py", line 51, in generalized_box_iou
    assert (boxes1[:, 2:] >= boxes1[:, :2]).all()
AssertionError
```

**Comment by timmeinhardt** [comment]
Does this error occur immediately or after a few iterations? The former would be very strange indeed. I think this is related to your input data. You should debug the data flow and check if everything works as when training on CrowdHuman. For example is this code after the if statement executed properly:

https://github.com/timmeinhardt/trackformer/blob/686fe60858e4f61497a4544b95f94487614d0741/src/trackformer/datasets/coco.py#L64

**Comment by ConsciousML** [comment]
Ok will check that just now.

I discovered that in Visdom, my training images seemed cut. Apparently is it not the case when I train with CrowdHuman:
[visdom.pdf](https://github.com/timmeinhardt/trackformer/files/6609776/visdom.pdf)

**Comment by ConsciousML** [comment]
>
You should debug the data flow and check if everything works as when training on CrowdHuman. For example is this code after the if statement executed properly:
> 
> https://github.com/timmeinhardt/trackformer/blob/686fe60858e4f61497a4544b95f94487614d0741/src/trackformer/datasets/coco.py#L64

I debugged and didn't notice anything weird. My guess is that maybe because the RandomSizeCrop is more aggressive on my data, maybe at some point it crops out the detection ?

I will check without the RandomSizeCrop.

**Comment by timmeinhardt** [comment]
If it works for our CrowdHuman/MOT you have to figure out what the difference to your custom dataset is. You said the `boxes` in `assert (boxes1[:, 2:] >= boxes1[:, :2]).all()` contrains NaN values. This sounds like a problem that comes from training on your data. Not directly the data itself. Does the loss for a particular iteration go up a lot? What happens if you run a training and set the learning rates to zero. Does the error still occur?

**Comment by ConsciousML** [comment]
I noticed that when I face the assert, the `out_bbox` contains Nans. I suppose it is the prediction of the model.
https://github.com/timmeinhardt/trackformer/blob/686fe60858e4f61497a4544b95f94487614d0741/src/trackformer/models/matcher.py#L71

Same thing when I set the lr to 0.

I will go up to see where the Nans first appear.

**Comment by ConsciousML** [comment]
The encoder seems to work fine, the Nans appear in the decoder:
https://github.com/timmeinhardt/trackformer/blob/686fe60858e4f61497a4544b95f94487614d0741/src/trackformer/models/deformable_transformer.py#L189

I will debug inside it

**Comment by ConsciousML** [comment]
It might be the encoder, I found Nans here:
https://github.com/timmeinhardt/trackformer/blob/686fe60858e4f61497a4544b95f94487614d0741/src/trackformer/models/deformable_transformer.py#L159

**Comment by ConsciousML** [comment]
I noticed that the Nans first appears in the `query_embed` variable:
https://github.com/timmeinhardt/trackformer/blob/686fe60858e4f61497a4544b95f94487614d0741/src/trackformer/models/deformable_detr.py#L167

Do you have any clue where this is updated ?

**Comment by timmeinhardt** [comment]
But you said NaNs appear even if you set all the learning rates to zero? This would be contradictive to the query embeddings becoming zero. Double check if this still happens if you set all rates to zero or comment out the optimizer step.

**Comment by ConsciousML** [comment]
You were right !
I might forgot to set a lr to 0.
When I comment the optimizer step, it successfully runs a whole epoch.

**Comment by ConsciousML** [comment]
Hi @timmeinhardt,

I'm still stuck and can't fix the problem.
Any idea about xhat to do ?

**Comment by timmeinhardt** [comment]
How do the loss values develop until the network produces NaN output values? If for example the bounding box loss goes up there might be something wrong with that.

**Comment by ConsciousML** [comment]
The overall loss before crash is:
```bash
7.164515495300293
4.680170059204102
4.274537086486816
5.886708736419678
4.5304131507873535
3.8330774307250977
7.964834690093994
3.0583243370056152
4.674091339111328
3.301724672317505
3.608858346939087
2.8133819103240967
2.8961634635925293
2.8605575561523438
3.1516401767730713
3.2725605964660645
2.9872331619262695
1.8360798358917236
2.4671669006347656
```

I logged this value:
https://github.com/timmeinhardt/trackformer/blob/686fe60858e4f61497a4544b95f94487614d0741/src/trackformer/engine.py#L120

**Comment by timmeinhardt** [comment]
Our code logs loss values in the command line or via Visdom. You should use these outputs to debug your results.

**Comment by ConsciousML** [comment]
Unfortunately, because the training crashes very early, the losses do not appear in visdom.

**Comment by timmeinhardt** [comment]
You could set `vis_and_log_interval=1` to see results after each iteration.

**Comment by ConsciousML** [comment]
Nice, that worked.

![newplot](https://user-images.githubusercontent.com/6661264/121907943-d32b0880-cd2c-11eb-9b03-cbe8c06d9720.png)

But yeah, it looks like the losses are not the issue.
I have no idea what to do ;(

**Comment by timmeinhardt** [comment]
Maybe there is something to be seen in the Visdom logging of the network outputs? Have you tried deactivating all data augmentations?

**Comment by ConsciousML** [comment]
Except that there is a lot of region proposal, it seems fine.
The groundtruths are well places.

I just tried the deactivate all augmentations an I had the same results. Maybe it comes from the augmentation that creates the "fake" previous frame. 

I have the following questions:
    1. Do you know how can I try to train without generating the previous frame if possible ?
    2. Where does the `query_embed` comes from and how is it different from `features` ?
  
https://github.com/timmeinhardt/trackformer/blob/686fe60858e4f61497a4544b95f94487614d0741/src/trackformer/models/deformable_detr.py#L167

https://github.com/timmeinhardt/trackformer/blob/686fe60858e4f61497a4544b95f94487614d0741/src/trackformer/models/deformable_detr.py#L135

**Comment by EMU1337X** [comment]
Man did u finally solved the problem? Eager to know how if so.
