### ISSUE TITLE
Please read & provide the following

### ISSUE THREAD

**Issue by niangea** [timmeinhardt/trackformer#81]
when I test demo,I get the right result in ubuntu,but I get the error in window
"Traceback (most recent call last):
  File "/tmp/pycharm_project_942/trackformer/src/track.py", line 276, in <module>
    main(dataset_name='DEMO',data_root_dir='data/snakeboard',output_dir='data/snakeboard',write_images='pretty')
  File "/home/lihenian/.conda/envs/bishe37/lib/python3.7/site-packages/sacred/config/captured_function.py", line 42, in captured_function
    result = wrapped(*args, **kwargs)
  File "/tmp/pycharm_project_942/trackformer/src/track.py", line 255, in main
    write_images, generate_attention_maps)
  File "/tmp/pycharm_project_942/trackformer/src/trackformer/util/track_utils.py", line 146, in plot_sequence
    cmap = rand_cmap(mx, type='bright', first_color_black=False, last_color_black=False)
  File "/tmp/pycharm_project_942/trackformer/src/trackformer/util/track_utils.py", line 94, in rand_cmap
    random_colormap = LinearSegmentedColormap.from_list('new_map', randRGBcolors, N=nlabels)
  File "/home/lihenian/.conda/envs/bishe37/lib/python3.7/site-packages/matplotlib/colors.py", line 796, in from_list
    if (isinstance(colors[0], Sized) and len(colors[0]) == 2
IndexError: list index out of range

Process finished with exit code 1"

I have used "ffmpeg -i data/snakeboard/snakeboard.mp4 -vf fps=30 data/snakeboard/%06d.png",but I still get this error

**Comment by timmeinhardt** [comment]
I do not have a windows computer and can not give you any advice on this. But it looks like `ffmpeg` can not find any png image files in `data/snakeboard`.

**Comment by niangea** [comment]
There are already pictures in snake, but I have a very strange thing when debugging, that is, the number of frames has decreased. Its pictures are taken every five, so there is a problem

**Comment by timmeinhardt** [comment]
But that happens for linux and windows, right? I think that is normal. Sorry I can not help you with the windows-specific issue.

**Comment by niangea** [comment]
yes,this happen in window,I get the right reslut in liunx

**Comment by niangea** [comment]
in the _sequence function， I found that it takes the order of every five，000001.png and 000005.png
