### ISSUE TITLE
ImportError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by hustmx721** [timmeinhardt/trackformer#89]
I follow the instruction from the closed issue #41 
my cuda version is 10.2,and pytorch version is 1.7.1,torchersion version is 0.8.1;other third-party dependency libraries are installed based on the instructions provided by install.md.
However，whether my pytorch version is 1.5.0 or another (torchvision is the equivalent), I get the same error when I run the demo code：
$ python src/track.py with \
    dataset_name=DEMO \
    data_root_dir=data/snakeboard \
    output_dir=data/snakeboard \
    write_images=pretty
Traceback (most recent call last):
  File "src/track.py", line 16, in <module>
    from trackformer.models import build_model
  File "/home/mist/trackformer/src/trackformer/models/__init__.py", line 6, in <module>
    from .deformable_transformer import build_deforamble_transformer
  File "/home/mist/trackformer/src/trackformer/models/deformable_transformer.py", line 17, in <module>
    from .ops.modules import MSDeformAttn
  File "/home/mist/trackformer/src/trackformer/models/ops/modules/__init__.py", line 1, in <module>
    from .ms_deform_attn import MSDeformAttn
  File "/home/mist/trackformer/src/trackformer/models/ops/modules/ms_deform_attn.py", line 11, in <module>
    from ..functions import MSDeformAttnFunction, ms_deform_attn_core_pytorch
  File "/home/mist/trackformer/src/trackformer/models/ops/functions/__init__.py", line 1, in <module>
    from .ms_deform_attn_func import MSDeformAttnFunction, ms_deform_attn_core_pytorch, ms_deform_attn_core_pytorch_mot
  File "/home/mist/trackformer/src/trackformer/models/ops/functions/ms_deform_attn_func.py", line 11, in <module>
    import MultiScaleDeformableAttention as MSDA
ImportError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory

**Comment by hustmx721** [comment]
I successfully solved this problem by upgrading my CUDA and pytorch versions.
Specifically, cuda version is 11.7 and pytorch version is 1.13.1.
pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 torchaudio==0.13.1 --extra-index-url https://download.pytorch.org/whl/cu117

**Comment by timmeinhardt** [comment]
Glad you solved the issue. Can we close it?
